FRETS_POSITION = 40, 100
FRET_SIZE = 16, 8

INITIAL_ACTIVE_FRETS = (False,) * 5
DRAW_SECONDS_AHEAD = 2
SPEED = 60
NOTE_WINDOW = 0.1  # second

SCENE_GAMEPLAY = 'SCENE_GAMEPLAY'

ASSETS_FRET_INACTIVE = 0
ASSETS_FRET_ACTIVE = 1
ASSETS_FRET_HIT = 2
ASSETS_NOTE = 3
ASSETS_NOTE_SMALL = 4
