FRETS_POSITION = 40, 100
FRET_SIZE = 16, 8

FRETS = [0.2, 0.4, 0.6, 0.8, 1]
TABS_DIR = 'tabs'

INITIAL_ACTIVE_FRETS = (False,) * len(FRETS)
DRAW_SECONDS_AHEAD = 2
SPEED = 60
NOTE_WINDOW = 0.1  # second

SCENE_GAMEPLAY = 'SCENE_GAMEPLAY'

ASSETS_FRET_INACTIVE = 0
ASSETS_FRET_ACTIVE = 1
ASSETS_FRET_HIT = 2
ASSETS_NOTE = 3
ASSETS_NOTE_SMALL = 4
